_BASE_: "../Base-RetinaNet.yaml"
MODEL:
  WEIGHTS: "/workdir/detectron2/output/vehicle-det-retinanet-finetune/model_final.pth"
  RESNETS:
    DEPTH: 50
  BACKBONE:
    FREEZE_AT: 5
  RETINANET:
    NUM_CLASSES: 2

INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
  FORMAT: BGR

DATASETS:
  TRAIN: ('vehicle_train',)
  TEST: ('vehicle_test',)

SOLVER:
  STEPS: (10000, 15000)
  MAX_ITER: 20000
  IMS_PER_BATCH: 4
  BASE_LR: 0.001
  CHECKPOINT_PERIOD: 1000
  WARMUP_ITERS: 0

DATALOADER:
  NUM_WORKERS: 4

OUTPUT_DIR: ./output/vehicle-det-retinanet-finetune