_BASE_: "./Base-RetinaNet.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  BACKBONE:
    FREEZE_AT: 5
  RETINANET:
    NUM_CLASSES: 3

INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
  FORMAT: BGR

DATASETS:
  TRAIN: ('vehicle_train',)
  TEST: ('vehicle_test',)

SOLVER:
  STEPS: (10000, 20000)
  MAX_ITER: 30000
  IMS_PER_BATCH: 4
  BASE_LR: 0.001
  CHECKPOINT_PERIOD: 1000
  WARMUP_ITERS: 1000

DATALOADER:
  NUM_WORKERS: 4

OUTPUT_DIR: ./output/vehicle-det-retinanet